### ISSUE TITLE
Over Query

### ISSUE THREAD

**Issue by TheWolfenstein** [BasvanH/habpanel-widget-googlemaps#2]
Thganks for this widget, got it working however i constantly got this window popup message: Directions request failed due to OVER_QUERY_LIMIT so i guess it has to do with the API and the reccuring refresh? If so, how can i change the refresh interval?

Thanks in advance

**Comment by BasvanH** [comment]
With the [latest version](https://github.com/BasvanH/habpanel-widget-googlemaps/pull/4) this is fixed.
